# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkTest
     pod 'Alamofire', '~> 4.5'
     pod 'SwiftyJSON'
     pod 'SVProgressHUD'

  target 'NetworkTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
